### ISSUE TITLE
Not able to work with all the options available

### ISSUE THREAD

**Issue by Github743** [softgandhi/ngQuiz#2]
I made the following changes to the configuration which are highlighted in bold

$scope.defaultConfig = {
        'allowBack': true,
        'allowReview': true,
        'autoMove': false,  // if true, it will move to next question automatically when answered.
        **'duration': 1**,  // indicates the time in which quiz needs to be completed. post that, quiz will be automatically submitted. 0 means unlimited.
        'pageSize': 1,
        **'requiredAll': true,**  // indicates if you must answer all the questions before submitting.
        'richText': false,
        **'shuffleQuestions': true,
        'shuffleOptions': ture,**
        'showClock': true,
        'showPager': true,
        'theme': 'none'
    }

But I am unable to see the clock and timer running, also shuffle options is also not working as expected so can you help me

**Comment by softgandhi** [comment]
Agreed that these four stuffs has not been implemented.
Will implement it soon.

**Comment by Github743** [comment]
For all who wants to shuffle the answers try this

`$scope.randomAnswers = function (q) {
             $scope.questions.forEach(function (q, index) 
            {

```
        $scope.questions[index].Options = $scope.config.shuffleOptions ? helper.shuffle($scope.questions[index].Options) : $scope.questions[index].Options;
        //$scope.setSelected(option.isAnswer, helper.toBool(option.Selected))

        //$scope.questions.Options = $scope.config.shuffleQuestions ? helper.shuffle(res.question) : res.question;
    });
}`
```

Call this function under loadQuiz after loading questions as follows
`$scope.randomAnswers($scope.questions);`

**Comment by softgandhi** [comment]
Thank you my friend. I have implemented the feature with a little bit of optimization.

```
$scope.shuffleOptions = function(){
        $scope.questions.forEach(function (question) {
           question.Options = helper.shuffle(question.Options);
        });
    }
```

Call this in loadQuiz function like: 

```
if($scope.config.shuffleOptions)
                $scope.shuffleOptions();
```

This change have been commited. So, closing this issue. Any feedback are welcome.
